config/routes.rb
TeamRegistration::Application.routes.draw do
  resources :staff_members, :except => [:show]

  get "dogs/index"

  get "dogs/new"

  get "dogs/create"

  get "dogs/edit"

  get "dogs/destroy"

    root :to => "index#index"

    devise_for :users, :skip => ['sessions', 'registrations']

    devise_scope :user do 
        get "/new_user" => "registration#new", :as => 'new_user_registration'
        post "/new_user" => "registration#create", :as => 'create_user_registration'
        get "/users" => "registration#index", :as => 'list_users'
        delete "/user/:id" => "registration#destroy", :as => 'delete_user'
        get "/user/:id/resend_email" => "registration#resend_email", :as => 'user_resend_email'

        get "/login" => "devise/sessions#new", :as => 'new_user_session'
        post "/login" => "devise/sessions#create", :as => 'user_session'
        delete "/logout" => "devise/sessions#destroy", :as => 'destroy_user_session'

        get "/user/:id/switch_country" => "registration#switch_show_country", :as => 'switch_show_country'
    end

    resources :teams
    resources :dogs

    match "/confirmation" => "confirmation#index", :as => 'confirmation_index'
    match "/confirmation/confirm_all" => "confirmation#confirm_all", :as => 'confirmation_confirm_all'
    match "/confirmation/payment_information" => "confirmation#payment_information", :as => 'confirmation_payment_information'
    match "/all_handlers/:country_id/:language" => "index#all_handlers"

    match "/payments/:id/confirm" => "index#confirm_payment", :as => 'payment_confirmation'
    delete "/payments/:id" => "index#delete_payment", :as => 'delete_payment'
    match "/number_information" => "index#number_information"

    match "/export/generate_random_startnumbers" => "export#generate_random_startnumbers"
    match "/export/katalog" => "export#catalogue"
    match "/export/size_and_breed_stats" => "export#size_and_breed_stats"
    match "/export/shirts" => "export#shirts"
    match "/export/generate_squad_numbers" => "export#generate_squad_numbers"
    match "/export/squads" => "export#squads"
    match "/export/for_main_judge" => "export#for_main_judge"
    match "/export/non_competing_dogs" => "export#non_competing_dogs"

    scope '/api', defaults: { format: 'json' }, constraints: { format: 'json' } do
        match "/countries" => "api#countries"
        match "/team/:country" => "api#country_teams"
        match "/team/v2/:country" => "api#country_teams_v2"
    end

end

app/models/dog.rb
class Dog < ActiveRecord::Base
    def self.microchip_positions
        {
            "RN" => I18n.t('activerecord.attributes.dog.microchip_positions.right_side_of_neck'),
            "LN" => I18n.t('activerecord.attributes.dog.microchip_positions.left_side_of_neck'),
            "O" => I18n.t('activerecord.attributes.dog.microchip_positions.other'),
        }
    end

    attr_accessible :name,
        :date_of_birth,
        :microchip,
        :microchip_position,
        :owner_address,
        :owner_first_name,
        :owner_last_name,
        :owner_phone_number,
        :tatoo,
        :sex,
        :country_id
  
    validates_presence_of :name,
        :date_of_birth,
        :microchip,
        :owner_first_name,
        :owner_last_name,
        :sex,
        :country_id

  validates_format_of :sex, :with => /M|F/
  validates_inclusion_of :microchip_position, in: Dog.microchip_positions.keys

  def country_text
      Country.find_country_by_number("0" * (3 - country_id.to_s.length) + country_id.to_s).name
  end

  def self.to_csv
      attributes = %w{ country_text name date_of_birth tatoo sex microchip microchip_position owner_address owner_first_name owner_last_name owner_phone_number }

      CSV.generate(headers: true) do |csv|
          csv << attributes

          current_scope.each do |team|
              csv << attributes.map{ |attr| team.send(attr) }
          end
      end
  end
end

app/controllers/dogs_controller.rb
class DogsController < ApplicationController
  before_filter :authenticate_user!
  before_filter :check_if_confirmed, :only => [:new, :create, :edit, :update, :destroy]
  authorize_resource :dog

  def index
      if current_user.admin? || current_user.superadmin?
          @dogs = Dog.all
          @countries = {}
          @dogs.each do |t|
              country_name = Country.find_country_by_number("0" * (3 - t.country_id.to_s.length) + t.country_id.to_s).name
              @countries[country_name] ||= []
              @countries[country_name] << t
          end
      elsif 
          @dogs = Dog.all(:conditions => { :country_id => current_user.country_id })
      end
      @dogs.each do |t|
          authorize! :read, t
      end
  end

  def show
    @dog = Dog.find(params[:id])
    check_users_country
    authorize! :read, @dog
  end

  def new
    @dog = Dog.new
    authorize! :create, @dog
  end

  def edit
    @dog = Dog.find(params[:id])
    check_users_country
    authorize! :update, @dog
  end

  def create
      @dog = Dog.new(params[:dog])
      if not current_user.superadmin?
          @dog.country_id = current_user.country_id
      else 
          @dog.country_id = Country[params[:dog][:country_id]].number
      end
      authorize! :create, @dog
      if @dog.save
          redirect_to dogs_path, :notice => t('dogs.controller.successfully_created')
      else
          render :action => 'new'
      end
  end

  def update
      @dog = Dog.find(params[:id])
      check_users_country
      country_id = @dog.country_id
      if @dog.update_attributes(params[:dog])
          @dog.country_id = country_id
          @dog.save
          redirect_to dogs_path, :notice => t('dogs.controller.successfully_updated')
      else
          render :action => 'edit'
      end
      authorize! :update, @dog
  end

  def destroy
      @dog = Dog.find(params[:id])
      authorize! :destroy, @dog
      check_users_country
      @dog.destroy
      redirect_to dogs_path, :notice => t('dogs.controller.successfully_deleted')
  end

    private
        def check_users_country
            unless current_user.admin? || current_user.superadmin? || @dog.country_id == current_user.country_id
                redirect_to action: :index, :notice => t('dogs.controller.dont_have_permission') 
                yield
            end
        end

        def check_if_confirmed
            if Payment.find_by_country_id(current_user.country_id)
                flash[:error] = t('dogs.controller.no_changed_allowed')
                redirect_to dogs_path
            end
        end
end

app/helpers/dogs_helper.rb
module DogsHelper
    def microchip_position_select(form, field, options = {})
        form.select(field, Dog.microchip_positions.map { |k, v| [v, k] }, options)
    end
end

app/views/dogs/_form.html.erb
<%= form_for(@dog, :html => {:class => 'form-horizontal well' }) do |f| %>
    <% unless @dog.errors.full_messages.empty? %>
        <div class="alert alert-error">
            <button class="close" data-dismiss="alert">×</button>
            <h3><%= t 'teams.form.correct_errors' %></h3>
            <ul>
                <% @dog.errors.full_messages.each do |msg| %>
                    <li><%= msg %></li>
                <% end %>
            </ul>
        </div>
    <% end %>

  <fieldset>
      <% if current_user.superadmin? %>
          <div class="control-group">
              <%= f.label :country_id, :class => 'control-label' %>
              <div class="controls">
                  <%= f.country_select :country_id %>
              </div>
          </div>
      <% end %>

      <div class="control-group">
          <%= f.label :name,  :class => 'control-label' %>
          <div class="controls">
              <%= f.text_field :name %>
          </div>
      </div>

      <div class="control-group">
          <%= f.label :sex, :class => 'control-label' %> 
          <div class="controls">
              <%= f.select(:sex, [[t('teams.form.male'), "M"], [t('teams.form.female'), "F"]]) %>
          </div>
      </div>

      <div class="control-group">
          <%= f.label :date_of_birth,  :class => 'control-label' %> 
          <div class="controls">
              <%= f.date_select :date_of_birth, :start_year => Time.now.year - 20, :end_year => Time.now.year  %>
          </div>
      </div>

      <div class="control-group">
          <%= f.label :microchip,  :class => 'control-label' %> 
          <div class="controls">
              <%= f.text_field :microchip %>
          </div>
      </div>

      <div class="control-group">
          <%= f.label :tatoo, :class => 'control-label' %> 
          <div class="controls">
              <%= f.text_field :tatoo %>
          </div>
      </div>


      <div class="control-group">
          <%= f.label :microchip_position, :class => 'control-label' %> 
          <div class="controls">
              <%= microchip_position_select(f, :microchip_position) %>
          </div>
      </div>


      <h3><%= t('activerecord.models.owner') %></h3>

      <div class="control-group">
          <%= f.label :owner_first_name, :class => 'control-label' %> 
          <div class="controls">
              <%= f.text_field :owner_first_name %>
          </div>
      </div>

      <div class="control-group">
          <%= f.label :owner_last_name, :class => 'control-label' %> 
          <div class="controls">
              <%= f.text_field :owner_last_name %>
          </div>
      </div>

      <div class="control-group">
          <%= f.label :owner_phone_number,  :class => 'control-label' %> 
          <div class="controls">
              <%= f.text_field :owner_phone_number %>
          </div>
      </div>

      <div class="control-group">
          <%= f.label :owner_address, :class => 'control-label' %> 
          <div class="controls">
              <%= f.text_area :owner_address, :rows => 5 %>
          </div>
      </div>
  </fieldset>
  <hr />

    <div class="form-actions">
        <%= f.submit t('teams.form.submit'), :class => 'btn btn-primary' %>
        <%= link_to t('links.teams.back'), dogs_path, :class => 'btn' %>
    </div>
<% end %>

app/views/dogs/create.html.erb
<h1>Dogs#create</h1>
<p>Find me in app/views/dogs/create.html.erb</p>

app/views/dogs/destroy.html.erb
<h1>Dogs#destroy</h1>
<p>Find me in app/views/dogs/destroy.html.erb</p>

app/views/dogs/edit.html.erb
<h1>Editing dog</h1>

<%= render 'form' %>

app/views/dogs/index.html.erb
<h1><%= t 'links.application.non_competing_dogs' %> </h1>
<br />

<% if current_user.admin? || current_user.superadmin? %>
    <% @countries.sort.each do |country, dogs| %>
        <h2><%= country %></h2>
        <table class="table">
            <tr>
                <th>Jméno</th>
                <th>Země</th>
                <% if current_user.superadmin? %>
                    <th>Akce</th>
                <% end %>
            </tr>

            <% dogs.each do |dog| %>
                <tr onclick="location.href='<%= dog_path(dog) %>'">
                    <td><%= dog.name %></td>
                    <td><%= Country.find_country_by_number("0" * (3 - dog.country_id.to_s.length)  + dog.country_id.to_s).name  %></td>
                    <% if current_user.superadmin? %>
                        <td><%= link_to "Smazat", dog, :method => :delete,  :class => "btn", :confirm => "Opravdu?" %> <%= link_to t('links.teams.edit'), edit_dog_path(dog), :class => "btn" %>
                    <% end %>
                </tr>
            <% end %>
        </table>
    <% end %>
<% else %>
    <table class="table">
        <tr>
            <th><%= t 'activerecord.attributes.dog.name' %></th>
            <th><%= t 'teams.form.actions' %></th>
        </tr>

        <% @dogs.each do |dog| %>
            <tr>
                <td><%= dog.name %></td>
                <td><%= link_to t('links.teams.show'), dog, :class => "btn" %> <%= link_to t('links.teams.edit'), edit_dog_path(dog), :class => "btn" %>
                    <%= link_to t('links.teams.destroy'), dog, :method => :delete, :data => { :confirm => 'Are you sure?' }, :class => "btn" %></td>
            </tr>
        <% end %>
    </table>
<% end %>
<br />

<% if not current_user.admin? %>
    <%= link_to t('teams.form.add_dog'), new_dog_path, :class => "btn" %>
<% end %>

app/views/dogs/new.html.erb
<h1><%= t('teams.form.add_dog') %></h1>

<%= render 'form' %>

app/views/dogs/show.html.erb
<table class="table">
    <tr>
        <th><%= t('teams.form.registered_name') %></th>
        <th><%= t('activerecord.attributes.dog.date_of_birth') %></th>
        <th><%= t('activerecord.attributes.dog.microchip') %></th>
    </tr>
    <tr>
        <td><%= @dog.name %></td>
        <td><%= @dog.date_of_birth %></td>
        <td><%= @dog.microchip %></td>
    <tr>
</table>

<% if not current_user.admin? %>
    <%= link_to t('links.teams.edit'), edit_dog_path(@dog), :class => "btn" %>
<% end %>
<%= link_to t('links.teams.back'), dogs_path, :class => "btn" %>