config/routes.rb
TeamRegistration::Application.routes.draw do
  resources :staff_members, :except => [:show]

  get "dogs/index"

  get "dogs/new"

  get "dogs/create"

  get "dogs/edit"

  get "dogs/destroy"

    root :to => "index#index"

    devise_for :users, :skip => ['sessions', 'registrations']

    devise_scope :user do 
        get "/new_user" => "registration#new", :as => 'new_user_registration'
        post "/new_user" => "registration#create", :as => 'create_user_registration'
        get "/users" => "registration#index", :as => 'list_users'
        delete "/user/:id" => "registration#destroy", :as => 'delete_user'
        get "/user/:id/resend_email" => "registration#resend_email", :as => 'user_resend_email'

        get "/login" => "devise/sessions#new", :as => 'new_user_session'
        post "/login" => "devise/sessions#create", :as => 'user_session'
        delete "/logout" => "devise/sessions#destroy", :as => 'destroy_user_session'

        get "/user/:id/switch_country" => "registration#switch_show_country", :as => 'switch_show_country'
    end

    resources :teams
    resources :dogs

    match "/confirmation" => "confirmation#index", :as => 'confirmation_index'
    match "/confirmation/confirm_all" => "confirmation#confirm_all", :as => 'confirmation_confirm_all'
    match "/confirmation/payment_information" => "confirmation#payment_information", :as => 'confirmation_payment_information'
    match "/all_handlers/:country_id/:language" => "index#all_handlers"

    match "/payments/:id/confirm" => "index#confirm_payment", :as => 'payment_confirmation'
    delete "/payments/:id" => "index#delete_payment", :as => 'delete_payment'
    match "/number_information" => "index#number_information"

    match "/export/generate_random_startnumbers" => "export#generate_random_startnumbers"
    match "/export/katalog" => "export#catalogue"
    match "/export/size_and_breed_stats" => "export#size_and_breed_stats"
    match "/export/shirts" => "export#shirts"
    match "/export/generate_squad_numbers" => "export#generate_squad_numbers"
    match "/export/squads" => "export#squads"
    match "/export/for_main_judge" => "export#for_main_judge"
    match "/export/non_competing_dogs" => "export#non_competing_dogs"

    scope '/api', defaults: { format: 'json' }, constraints: { format: 'json' } do
        match "/countries" => "api#countries"
        match "/team/:country" => "api#country_teams"
        match "/team/v2/:country" => "api#country_teams_v2"
    end

end

app/views/index/_all_handlers.html.erb
<% if not @country_name.empty? %>
<% end %>
<% if @handlers.empty? %>
<% else %>
    <br />
    <table class="handlers">
        <th></th>
        <th><%= t 'teams.form.first_name' %></th>
        <th><%= t 'teams.form.last_name' %></th>
        <th><%= t 'activerecord.models.dog' %></th>
        <th><%= t 'activerecord.attributes.team.category' %></th>
        <th><%= t 'activerecord.attributes.dog.breed_id' %></th>
        <% @handlers.each do |handler| %>
            <% handler.dogs.all.each do |dog| %>
                <tr>
                    <td><img src="http://agility2012.cz/team_registration<%= handler.picture.url(:big_thumb) %>" /></td>
                    <td><%= handler.first_name %></td>
                    <td><%= handler.last_name %></td>
                    <td><%= dog.registered_name %></td>
                    <td><%= dog.category %></td>
                    <td><%= Breed.find(dog.breed_id).name %></td>
                </tr>
            <% end %>
        <% end %>
    </table>
<% end %>

app/views/index/index.html.erb
<% if current_user && (current_user.admin? || current_user.superadmin?) %>
    <h1>Seznam plateb</h1>
    <table class="table">
        <tr>
            <th>Variabilní symbol</th>
            <th>Částka (eur)</th>
            <th>Země</th>
            <th>Potvrzeno</th>
            <th>Akce</th>
        </tr>
        <% if @payments %>
            <% @payments.each do |payment| %>
                <tr>
                    <td><%= 22220000 + payment.id %></td>
                    <td><%= payment.price_in_euros %></td>
                    <td><%= Country.find_country_by_number("0" * (3 - payment.country_id.to_s.length)  + payment.country_id.to_s).name  %></td>
                    <td><% if payment.confirmed %>Ano<% else %><%= link_to "Potvrdit platbu", payment_confirmation_path(:id => payment.id), :class => 'btn', :confirm => 'Opravdu chcete potvrdit platbu s variabilním symbolem %d?' % [(payment.id + 22220000)] %><% end %></td>
                    <td><%= link_to "Smazat", delete_payment_path(payment.id), :method => :delete, :confirm => 'Opravdu chcete smazat platbu s variabilním symbolem %d?' % (payment.id + 22220000), :class => 'btn' %></td>
                </tr>
            <% end %>
        <% end %>
    </table>
<% end %>

app/views/index/number_information.html.erb
<h1><%= t 'index.number_information.title' %></h1>
<table class="table">
    <thead>
        <th><%= t 'index.number_information.vest_size' %></th>
        <th>XXS</th>
        <th>XS</th>
        <th>S</th>
        <th>M</th>
        <th>L</th>
        <th>XL</th>
    </thead>
    <tbody>
        <tr>
            <td><%= t 'index.number_information.number_height' %></td>
            <td>40</td>
            <td>45</td>
            <td>50</td>
            <td>55</td>
            <td>60</td>
            <td>65</td>
        </tr>
        <tr>
            <td><%= t 'index.number_information.number_width' %></td>
            <td>40</td>
            <td>43</td>
            <td>46</td>
            <td>49</td>
            <td>52</td>
            <td>55</td>
        </tr>
    </tbody>
</table>

<div class="alert alert-info">
    <p><%= t 'index.number_information.width_not_circumference' %></p>
    <p><%= t 'index.number_information.detailed_info' %></p>
</div>

<%= image_tag "dres_cislo.png" %>