config/routes.rb
TeamRegistration::Application.routes.draw do
  resources :staff_members, :except => [:show]

  get "dogs/index"

  get "dogs/new"

  get "dogs/create"

  get "dogs/edit"

  get "dogs/destroy"

    root :to => "index#index"

    devise_for :users, :skip => ['sessions', 'registrations']

    devise_scope :user do 
        get "/new_user" => "registration#new", :as => 'new_user_registration'
        post "/new_user" => "registration#create", :as => 'create_user_registration'
        get "/users" => "registration#index", :as => 'list_users'
        delete "/user/:id" => "registration#destroy", :as => 'delete_user'
        get "/user/:id/resend_email" => "registration#resend_email", :as => 'user_resend_email'

        get "/login" => "devise/sessions#new", :as => 'new_user_session'
        post "/login" => "devise/sessions#create", :as => 'user_session'
        delete "/logout" => "devise/sessions#destroy", :as => 'destroy_user_session'

        get "/user/:id/switch_country" => "registration#switch_show_country", :as => 'switch_show_country'
    end

    resources :teams
    resources :dogs

    match "/confirmation" => "confirmation#index", :as => 'confirmation_index'
    match "/confirmation/confirm_all" => "confirmation#confirm_all", :as => 'confirmation_confirm_all'
    match "/confirmation/payment_information" => "confirmation#payment_information", :as => 'confirmation_payment_information'
    match "/all_handlers/:country_id/:language" => "index#all_handlers"

    match "/payments/:id/confirm" => "index#confirm_payment", :as => 'payment_confirmation'
    delete "/payments/:id" => "index#delete_payment", :as => 'delete_payment'
    match "/number_information" => "index#number_information"

    match "/export/generate_random_startnumbers" => "export#generate_random_startnumbers"
    match "/export/katalog" => "export#catalogue"
    match "/export/size_and_breed_stats" => "export#size_and_breed_stats"
    match "/export/shirts" => "export#shirts"
    match "/export/generate_squad_numbers" => "export#generate_squad_numbers"
    match "/export/squads" => "export#squads"
    match "/export/for_main_judge" => "export#for_main_judge"
    match "/export/non_competing_dogs" => "export#non_competing_dogs"

    scope '/api', defaults: { format: 'json' }, constraints: { format: 'json' } do
        match "/countries" => "api#countries"
        match "/team/:country" => "api#country_teams"
        match "/team/v2/:country" => "api#country_teams_v2"
    end

end

app/models/staff_member.rb
class StaffMember < ActiveRecord::Base
    include StaffMembersHelper
    attr_accessible :full_name,
        :role_type,
        :picture,
        :number_size,
        :phone_number,
        :email,
        :country_id

    validates_presence_of :full_name,
        :role_type,
        :phone_number

    validates_presence_of :number_size, if: "role_type == 1"

    validates_format_of :number_size, :with => /XXS|XS|S|M|L|XL/
        
    validates_inclusion_of :role_type, :in => 1..5

    has_attached_file :picture, :styles => { :big_thumb => '120x120', :portrait => "150x200" }, :path => ":rails_root/public/system/:class/:attachment/:id/:style/:filename", :url => '/system/:class/:attachment/:id/:style/:filename', :convert_options => { :portrait => "-quality 75" }
    validates_attachment_presence :picture
    validates_attachment_size :picture, :less_than => 5.megabytes
    validates_attachment_content_type :picture, content_type: ['image/jpeg', 'image/png', 'image/gif']

    validate :check_maximum_count

    def check_maximum_count
        if StaffMember.where(:country_id => country_id).count > 4
            errors.add(:base, I18n.t('teams.form.maximum_staff_count'))
        end
    end

    def role_name
        possible_roles[role_type]
    end

    def as_json(*a)
        lang = I18n.locale
        I18n.locale = 'cs'
        role_cs = role_name

        I18n.locale = 'en'
        role_en = role_name

        I18n.locale = lang
        {
            "full_name" => full_name,
            "role_cs" => role_cs,
            "role_en" => role_en,
            "picture_url" => picture.url(:portrait),
            "show_role" => role_type < 5
        }
    end

    def country_text
        Country.find_country_by_number("0" * (3 - country_id.to_s.length) + country_id.to_s).name
    end

    def self.to_csv
        attributes = %w{ id country_text full_name role_name number_size phone_number email }

        CSV.generate(headers: true) do |csv|
            csv << attributes

            current_scope.each do |team|
                csv << attributes.map{ |attr| team.send(attr) }
            end
        end
    end
end

app/controllers/staff_members_controller.rb
class StaffMembersController < ApplicationController
    before_filter :authenticate_user!
    before_filter :check_if_confirmed, :only => [:new, :create, :edit, :update, :destroy]
    authorize_resource :staff_member
    
    # GET /staff_members
    # GET /staff_members.json
    def index
        if current_user.admin? || current_user.superadmin?
            @staff_members = StaffMember.all
            @countries = {}
            @staff_members.each do |t|
                country_name = Country.find_country_by_number("0" * (3 - t.country_id.to_s.length) + t.country_id.to_s).name
                @countries[country_name] ||= []
                @countries[country_name] << t
            end
        elsif 
            @staff_members = StaffMember.all(:conditions => { :country_id => current_user.country_id })
        end
        @staff_members.each do |t|
            authorize! :read, t
        end
    end

    # GET /staff_members/1
    # GET /staff_members/1.json
    def show
        @staff_member = StaffMember.find(params[:id])
        check_users_country
        authorize! :read, @staff_member
    end

    # GET /staff_members/new
    # GET /staff_members/new.json
    def new
        @staff_member = StaffMember.new
        authorize! :create, @staff_member
    end

    # GET /staff_members/1/edit
    def edit
        @staff_member = StaffMember.find(params[:id])
        check_users_country
        authorize! :update, @staff_member
    end

    # POST /staff_members
    # POST /staff_members.json
    def create
        @staff_member = StaffMember.new(params[:staff_member])
        if not current_user.superadmin?
            @staff_member.country_id = current_user.country_id
        else 
            @staff_member.country_id = Country[params[:staff_member][:country_id]].number
        end
        authorize! :create, @staff_member
        if @staff_member.save
            redirect_to staff_members_path, :notice => t('staff_members.controller.successfully_created')
        else
            render :action => 'new'
        end
    end

    # PUT /staff_members/1
    # PUT /staff_members/1.json
    def update
        @staff_member = StaffMember.find(params[:id])
        if not check_users_country
            return
        end
        country_id = @staff_member.country_id
        if @staff_member.update_attributes(params[:staff_member])
            @staff_member.country_id = country_id
            @staff_member.save
            redirect_to staff_members_path, :notice => t('staff_members.controller.successfully_updated')
        else
            render :action => 'new'
        end
        authorize! :update, @staff_member
    end

    # DELETE /staff_members/1
    # DELETE /staff_members/1.json
    def destroy
        @staff_member = StaffMember.find(params[:id])
        authorize! :destroy, @staff_member
        if not check_users_country
            return
        end
        @staff_member.destroy
        redirect_to staff_members_path, :notice => t('staff_members.controller.successfully_deleted')
    end

    private
        def check_users_country
            if current_user.admin? || current_user.superadmin?
                return true
            end
            if @staff_member.country_id != current_user.country_id
                redirect_to staff_members_path, :notice => t('staff_members.controller.dont_have_permission')
                return false
            end
            return true
        end

        def check_if_confirmed
            if Payment.find_by_country_id(current_user.country_id)
                flash[:error] = t('staff_members.controller.no_changed_allowed')
                redirect_to staff_members_path
            end
        end
end

app/helpers/staff_members_helper.rb
module StaffMembersHelper
    def role_select(form, options = {})
        form.select(:role_type, possible_roles.map { |k, v| [v, k] }, options)
    end

    def possible_roles
        {
            1 => I18n.t('staff_members.model.teamleader'),
            2 => I18n.t('staff_members.model.first_assistant'),
            3 => I18n.t('staff_members.model.second_assistant'),
            4 => I18n.t('staff_members.model.physiotherapist'),
            5 => I18n.t('staff_members.model.other')
        }
    end
end

app/views/staff_members/_form.html.erb
<%= form_for(@staff_member, :html => {:class => 'form-horizontal well' }) do |f| %>
    <% unless @staff_member.errors.full_messages.empty? %>
        <div class="alert alert-error">
            <button class="close" data-dismiss="alert">×</button>
            <h3><%= t 'teams.form.correct_errors' %></h3>
            <ul>
                <% @staff_member.errors.full_messages.each do |msg| %>
                    <li><%= msg %></li>
                <% end %>
            </ul>
        </div>
    <% end %>


    <fieldset>
        <% if current_user.superadmin? %>
            <div class="control-group">
                <%= f.label :country_id, :class => 'control-label' %>
                <div class="controls">
                    <%= f.country_select :country_id %>
                </div>
            </div>
        <% end %>

        <div class="control-group">
            <%= f.label :full_name, :class => 'control-label' %>
            <div class="controls">
                <%= f.text_field :full_name %>
            </div>
        </div>

        <div class="control-group">
            <%= f.label :picture, :class => 'control-label' %>
            <% if @staff_member.picture_file_name %>
                <div class="span6">
                    <%= image_tag(@staff_member.picture.url(:big_thumb)) %>
                </div>
            <% end %>
            <div class="controls">
                <%= f.file_field :picture %>
            </div>
        </div>

        <div class="control-group">
            <%= f.label :role_type,  :class => 'control-label' %>
            <div class="controls">
                <%= role_select(f, {:onchange => "updateNumberSizeField()" }) %>
            </div>
        </div>

        <div class="control-group">
            <%= f.label :email, :class => 'control-label' %>
            <div class="controls">
                <%= f.email_field :email %>
            </div>
        </div>

        <div class="control-group">
            <%= f.label :phone_number, :class => 'control-label' %>
            <div class="controls">
                <%= f.text_field :phone_number %>
            </div>
        </div>

        <div id="number_size_wrapper">
        <div class="control-group">
            <%= f.label :number_size, :class => 'control-label' %>
            <div class="controls">
                <%= f.select :number_size, ["XXS", "XS", "S", "M", "L", "XL"] %>
                <a class="btn" href="/number_information" target="_blank"><i class="icon-large icon-question-sign"></i></a>
            </div>
        </div>
        </div>
    </fieldset>

    <div class="form-actions">
        <%= f.submit t('teams.form.submit'), :class => 'btn btn-primary' %>
        <%= link_to t('links.teams.back'), staff_members_path, :class => 'btn' %>
    </div>

    <script type="text/javascript">
function updateNumberSizeField() {
    var role_type = $('#staff_member_role_type').val();
    if (role_type === '1') {
        $('#number_size_wrapper').show();
    } else {
        $('#number_size_wrapper').hide();
    }
}

$(document).ready(function() {
    updateNumberSizeField();
    $('#staff_member_role_type').change(updateNumberSizeField);
});
    </script>
<% end %>

app/views/staff_members/edit.html.erb
<h1><%= t('activerecord.models.staff_member') %></h1>

<%= render 'form' %>

app/views/staff_members/index.html.erb
<h1><%= t 'staff_members.index.title' %> </h1>
<br />

<% if current_user.admin? || current_user.superadmin? %>
    <% @countries.sort.each do |country, staff_members| %>
        <h2><%= country %></h2>
        <table class="table">
            <tr>
                <th>Jméno</th>
                <th>Role</th>
                <th>Země</th>
                <% if current_user.superadmin? %>
                    <th>Akce</th>
                <% end %>
            </tr>

            <% staff_members.each do |staff_member| %>
                <tr>
                    <td><%= staff_member.full_name %></td>
                    <td><%= possible_roles[staff_member.role_type] %></th>
                    <td><%= Country.find_country_by_number("0" * (3 - staff_member.country_id.to_s.length)  + staff_member.country_id.to_s).name  %></td>
                    <% if current_user.superadmin? %>
                        <td><%= link_to "Smazat", staff_member, :method => :delete,  :class => "btn", :confirm => "Opravdu?" %> <%= link_to t('links.teams.edit'), edit_staff_member_path(staff_member), :class => "btn" %>
                    <% end %>
                </tr>
            <% end %>
        </table>
    <% end %>
<% else %>
    <table class="table">
        <tr>
            <th><%= t 'activerecord.attributes.staff_member.full_name' %></th>
            <th><%= t 'activerecord.attributes.staff_member.role_type' %></th>
            <th><%= t 'teams.form.actions' %></th>
        </tr>

        <% @staff_members.each do |staff_member| %>
            <tr>
                <td><%= staff_member.full_name %></td>
                <td><%= possible_roles[staff_member.role_type] %></th>
                <td><%= link_to t('links.teams.edit'), edit_staff_member_path(staff_member), :class => "btn" %>
                    <%= link_to t('links.teams.destroy'), staff_member, :method => :delete, :data => { :confirm => 'Are you sure?' }, :class => "btn" %></td>
            </tr>
        <% end %>
    </table>
<% end %>
<br />

<% if not current_user.admin? %>
    <%= link_to t('links.staff_members.new'), new_staff_member_path, :class => "btn" %>
<% end %>

app/views/staff_members/new.html.erb
<h1><%= t('activerecord.models.staff_member') %></h1>

<%= render 'form' %>

app/views/staff_members/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_staff_member_path(@staff_member) %> |
<%= link_to 'Back', staff_members_path %>