config/routes.rb
TeamRegistration::Application.routes.draw do
  resources :staff_members, :except => [:show]

  get "dogs/index"

  get "dogs/new"

  get "dogs/create"

  get "dogs/edit"

  get "dogs/destroy"

    root :to => "index#index"

    devise_for :users, :skip => ['sessions', 'registrations']

    devise_scope :user do 
        get "/new_user" => "registration#new", :as => 'new_user_registration'
        post "/new_user" => "registration#create", :as => 'create_user_registration'
        get "/users" => "registration#index", :as => 'list_users'
        delete "/user/:id" => "registration#destroy", :as => 'delete_user'
        get "/user/:id/resend_email" => "registration#resend_email", :as => 'user_resend_email'

        get "/login" => "devise/sessions#new", :as => 'new_user_session'
        post "/login" => "devise/sessions#create", :as => 'user_session'
        delete "/logout" => "devise/sessions#destroy", :as => 'destroy_user_session'

        get "/user/:id/switch_country" => "registration#switch_show_country", :as => 'switch_show_country'
    end

    resources :teams
    resources :dogs

    match "/confirmation" => "confirmation#index", :as => 'confirmation_index'
    match "/confirmation/confirm_all" => "confirmation#confirm_all", :as => 'confirmation_confirm_all'
    match "/confirmation/payment_information" => "confirmation#payment_information", :as => 'confirmation_payment_information'
    match "/all_handlers/:country_id/:language" => "index#all_handlers"

    match "/payments/:id/confirm" => "index#confirm_payment", :as => 'payment_confirmation'
    delete "/payments/:id" => "index#delete_payment", :as => 'delete_payment'
    match "/number_information" => "index#number_information"

    match "/export/generate_random_startnumbers" => "export#generate_random_startnumbers"
    match "/export/katalog" => "export#catalogue"
    match "/export/size_and_breed_stats" => "export#size_and_breed_stats"
    match "/export/shirts" => "export#shirts"
    match "/export/generate_squad_numbers" => "export#generate_squad_numbers"
    match "/export/squads" => "export#squads"
    match "/export/for_main_judge" => "export#for_main_judge"
    match "/export/non_competing_dogs" => "export#non_competing_dogs"

    scope '/api', defaults: { format: 'json' }, constraints: { format: 'json' } do
        match "/countries" => "api#countries"
        match "/team/:country" => "api#country_teams"
        match "/team/v2/:country" => "api#country_teams_v2"
    end

end

app/views/layouts/_notices.html.erb
<% if flash[:error] %>
    <p class="alert alert-error">
    <button class="close" data-dismiss="alert">×</button>
    <%= flash[:error] %></p>
    </p>
<% end %>
<% if flash[:alert] %>
    <p class="alert">
    <button class="close" data-dismiss="alert">×</button>
    <%= flash[:alert] %></p>
    </p>
<% end %>
<% if flash[:notice] %>
    <p class="alert alert-info">
    <button class="close" data-dismiss="alert">×</button>
    <%= flash[:notice] %></p>
    </p>
<% end %>
<% if flash[:success] %>
    <p class="alert alert-success">
    <button class="close" data-dismiss="alert">×</button>
    <%= flash[:success] %></p>
    </p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
    <head>
        <title><%= t 'application.title' %></title>
        <%= stylesheet_link_tag    "application", :media => "all" %>
        <%= javascript_include_tag "application" %>
        <%= csrf_meta_tags %>
        <meta charset="UTF-8">
    </head>
    <body>
        <div class="navbar navbar-fixed-top">
            <div class="navbar-inner">
                <div class="container">
                    <%= link_to t('application.title'), root_url, :class => "brand" %>
                    <% if user_signed_in? %>
                        <%= link_to t('links.application.logout'), destroy_user_session_path, :method => :delete, :class => "btn" %>
                    <% else %>
                        <%= link_to t('links.application.login'), new_user_session_path,  :class => "btn" %>
                    <% end %>
                </div>
            </div>
        </div>
    </div>
    <div class="container">
        <div class="row">
            <div class="span3">
                <div class="button-bar">
                    <div class="btn-group">
                        <%= link_to "cs", root_url(:locale => 'cs'), :class => "btn btn-small" %> 
                        <%= link_to "en", root_url(:locale => 'en'), :class => "btn btn-small" %> 
                        <%= link_to "es", root_url(:locale => 'es'), :class => "btn btn-small" %> 
                        <%= link_to "fr", root_url(:locale => 'fr'), :class => "btn btn-small" %> 
                        <%= link_to "de", root_url(:locale => 'de'), :class => "btn btn-small" %>
                    </div>
                </div>
                <br />
                <ul class="nav nav-tabs nav-stacked">
                    <% if signed_in? %>
                        <% if current_user.superadmin? %>
                            <li><%= link_to t('links.application.new_admin'), new_user_registration_path %></li>
                            <li><%= link_to t('links.application.teams'), teams_path %></li>
                            <li><%= link_to t('links.application.non_competing_dogs'), dogs_path %></li>
                            <li><%= link_to t('links.application.staff_members'), staff_members_path %></li>
                            <li><%= link_to "Platby", root_url %></li>
                            <li><%= link_to "Uživatelé", list_users_path %></li>
                        <% end %>
                        <% if current_user.admin? %>
                            <li><%= link_to t('links.application.new_user'), new_user_registration_path %></li>
                            <li><%= link_to t('links.application.teams'), teams_path %></li>
                            <li><%= link_to t('links.application.non_competing_dogs'), dogs_path %></li>
                            <li><%= link_to t('links.application.staff_members'), staff_members_path %></li>
                            <li><%= link_to "Platby", root_url %></li>
                            <li><%= link_to "Uživatelé", list_users_path %></li>
                        <% end %>
                        <% if current_user.user? %>
                            <li><%= link_to t('links.application.teams'), teams_path %></li>
                            <li><%= link_to t('links.application.non_competing_dogs'), dogs_path %></li>
                            <li><%= link_to t('links.application.staff_members'), staff_members_path %></li>
                        <% end %>
                        <% if current_user.confirm_all and current_user.user? %>
                            <li><%= link_to t('links.application.payment_information'), confirmation_payment_information_path %></li>
                        <% elsif current_user.user? %>
                            <li><%= link_to t('links.application.confirmation'), confirmation_index_path %></li>
                        <% end %>
                    <% end %>
                </ul>
            </div>
            <div class="span9">
                <%= render 'layouts/notices' %>
                <%= yield %>
            </div>
        </div>
    </div>
</body>
</html>